server:
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://172.0.0.1:3306/meal_db?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: meal
    password: mealmeal
  # redis config
  redis:
   host: localhost
   port: 6379
   database: 0

# mybatisPlus config
mybatis-plus:
  configuration:
   log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
   db-config:
    logic-delete-value: now()
    logic-not-delete-value: null

project:
  isDebug: true