server:
  port: 8088
  servlet:
    context-path: /meal/

# mybatisPlus config
mybatis-plus:
  configuration:
   log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
   db-config:
    logic-delete-value: now()
    logic-not-delete-value: null

project:
  isDebug: true

#COSconfig
qcloud:
  secretId: AKIDtfKwMZbS6Z7YmneIk281iDVZP5YnriMn
  secretKey: GI7i6HG2bx50iPD2e2GI7i5FCvRjomW3
  region: ap-guangzhou
  URL: https://jayma05-1326851618.cos.ap-guangzhou.myqcloud.com/
  bucketName: jayma05-1326851618

