server:
  port: 8088
  servlet:
    context-path: /meal/

jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES  #指定解密算法

# mybatisPlus config
mybatis-plus:
  configuration:
   log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted_at # 全局逻辑删除字段名
      logic-delete-value: now() # 逻辑已删除值
      logic-not-delete-value: null # 逻辑未删除值

project:
  isDebug: true

#COSconfig
qcloud:
  secretId: ENC(tJzlafN2XmskVdpt1dgmDirLMZpQ2Xo1rp8BVv/6N6dtT4OA57GAXIAVC6wGsBq6nnvPzh1Tuus=)
  secretKey: ENC(kN+VclXasPsL4uxNFp96BOFqaFLE7UbvX8eEhaDrAsV1jcnF6N3whiD9d1dLFRLP44sBlhhcaTg=)
  region: ap-guangzhou
  URL: https://jayma05-1326851618.cos.ap-guangzhou.myqcloud.com/
  bucketName: jayma05-1326851618

#邮箱配置
spring:
  mail:
    host: smtp.qq.com
    username: 2664894562@qq.com
    password: ENC(86S7x6gXjawtT5ZxqO53H5XJl+Zd8SPZOh7x8YvSvIgfX1GPcN9UlA==)
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    protocol: smtp
    port: 587
