server:
  port: 8088
  servlet:
    context-path: /meal/

jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES  #指定解密算法

# mybatisPlus config
mybatis-plus:
  configuration:
   log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
   db-config:
    logic-delete-value: now()
    logic-not-delete-value: null

project:
  isDebug: true

#COSconfig
qcloud:
  secretId: ENC(tJzlafN2XmskVdpt1dgmDirLMZpQ2Xo1rp8BVv/6N6dtT4OA57GAXIAVC6wGsBq6nnvPzh1Tuus=)
  secretKey: ENC(kN+VclXasPsL4uxNFp96BOFqaFLE7UbvX8eEhaDrAsV1jcnF6N3whiD9d1dLFRLP44sBlhhcaTg=)
  region: ap-guangzhou
  URL: https://jayma05-1326851618.cos.ap-guangzhou.myqcloud.com/
  bucketName: jayma05-1326851618

