project:
  resourceSaveLocation: /file/
  resourceAccessUrl: http://8.134.154.79:8088/resource/

spring:
  datasource:
    url: jdbc:mysql://8.134.154.79:3306/meal_db?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: meal
    password: mealmeal
  # redis config
  redis:
    host: 8.134.154.79
    port: 6379
    database: 1
    password: admin_redis